name: Publish GitHub Packages
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: MineInAbyss/publish-action@develop
        with:
          maven-metadata-url: https://repo.nexomc.com/releases/com/nexomc/protectionlib/maven-metadata.xml
          maven-snapshot-metadata-url: https://repo.nexomc.com/snapshots/com/nexomc/protectionlib/maven-metadata.xml
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PASSWORD }}
          release-files: |
            ${{ github.workspace }}/publish/*.jar